# Generated by Django 5.2.11 on 2026-02-11 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BtcPrice',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('price_pln', models.DecimalField(decimal_places=2, max_digits=18)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'btc_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10, unique=True)),
                ('must_set_password', models.BooleanField(default=True)),
                ('otp_code', models.CharField(blank=True, max_length=128, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
